Add pagination
ellabuysse/RecipeMatchApp pull request #27
Opened 2022-07-25 16:03 UTC by ellabuysse

Added pagination with spinner while cards are loading (can't add UI frames in background thread) . Also fixed collection view image bug by adding async call to get the image data before setting the image.

2022-07-26 16:24 UTC, michaeltabfb requested changes
So in general, this logic works!👍🏻
as i mentioned in the comments, kudos for start thinking how completion blocks can help you code better!💪🏻

few things though
- seems like this logic isn't implemented for when actually swiping the recipes to either of the sides (working when tapping the X\V buttons)
- this is pretty basic implementation of pagination. ideally you will not want the user the see a loader when loading a new page, but would want to have a smoother user experience. this is up to you what you want to do with this. again, it's working now, but i'd say it's not ideal - let me know if you want to brainstorm about ideas on how to achieve a smoother user experience here.

other then that, there are just few fixes that i'd like you to fix before we can merge it.

2022-07-26 16:24 UTC, michaeltabfb commented on RecipeMatch/Views/DraggableView.h
> +- (void)rightClickAction:(void (^)(BOOL succeeded, NSError *error))completion;
nice! i love seeing how you understand the power of completion blocks and when you can use it!💪🏻

2022-07-26 16:24 UTC, michaeltabfb commented on RecipeMatch/Views/DraggableViewBackground.m
> +    }];
i noticed that you call this `rightClickAction ` from `DraggableViewBackground`, then inside `rightClickAction` (that is in `DraggableView`) you call `delegate draggableViewCardSwipedRight`, which is in.... `DraggableViewBackground`..... do you see where i'm going with it?

2022-07-26 16:24 UTC, michaeltabfb commented on RecipeMatch/Views/DraggableViewBackground.m
> +    NSInteger allCardsIndex; // index of current card out of all cards
i find the naming of `cardsLoadedIndex ` and `allCardsIndex ` to be little confusing....any chance you can comeout with a better naming?

2022-07-26 16:24 UTC, michaeltabfb commented on RecipeMatch/Views/GridRecipeCell.h
> +@property (strong, nonatomic) NSString *hasImage;
doesn't seems to be in use

2022-07-26 21:29 UTC, ellabuysse commented on RecipeMatch/View Controllers/ProfileViewController.m
> +    [task resume];
I found some images weren't loading so I added this to get the image data before setting the image

2022-07-26 21:29 UTC, ellabuysse commented on RecipeMatch/View Controllers/ProfileViewController.m
> +                    GridRecipeCell *updateCell = (id)[collectionView cellForItemAtIndexPath:indexPath];
Added a comment for this

2022-07-27 15:57 UTC, michaeltabfb approved these changes
looks good.
i left few comments which i think would be worth visiting and iterating on

2022-07-27 15:57 UTC, michaeltabfb commented on RecipeMatch/View Controllers/ProfileViewController.m
> +    return cell;
few things.
- `recipe` is already a model object, so you can access it's image\name with `recipe.name`
-  `cell` is being passed to here (and not a copy), so no need to return it back
-  it's better to move this setup functionality to the cell it self, and do all of this from the there, and in `cellForItemAtIndexPath ` just call `[cell setupWithRecipe:self.recipes[indexPath.row]]`

2022-07-27 15:57 UTC, michaeltabfb commented on RecipeMatch/API/APIManager.m
> +        if (count > MIN_RECIPE_COUNT) {  // if there are enough recipes, return them
it might be worth adding more description here, like the logic and actual reasoning for it

2022-07-27 15:57 UTC, michaeltabfb commented on RecipeMatch/View Controllers/StreamViewController.m
> +            self.draggableBackground.recipes = recipes;
this actually needs to be fixed, otherwise might lead to a crash

2022-07-27 16:13 UTC, michaeltabfb commented
also, now that you added the sdWebImage library, you might want to change all other image loading methods to also use it. that way you'll get it benefits like caching and a lot of others

2022-07-28 17:27 UTC, merged

2022-07-28 17:32 UTC, michaeltabfb commented on RecipeMatch/Views/GridRecipeCell.m
>      [self.imageView cancelImageDownloadTask];
might as well just use the sdWebImage version for canceling `sd_cancelCurrentImageLoad`